spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xxx?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username:
    password: 
  profiles:
    active: dev
  mvc:
    #    static-path-pattern: /img/**
    #修改swagger路径匹配，兼容springboot2.6x以后版本
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  #  web:
  #    resources:
  #      static-locations: classpath:/img/**
  redis:
    database: 0 #使用的数据库号
    host:
    port:
    timeout: 5000
  session:
    store-type: redis
    timeout: 259200

mybatis-plus:
  mapper-locations: classpath:mybatis/mappers/**
  configuration:
    map-underscore-to-camel-case: false #关闭自动驼峰映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #数据库日志
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

server:
  port: 8080
  servlet:
    context-path: /api
